---
- name: Create grafana src folder
  file: path=/src/grafana state=directory

- name: Create grafana opt folder
  file: path=/opt/grafana state=directory

- name: Get source
  command: wget https://grafanarel.s3.amazonaws.com/builds/grafana-2.1.3.linux-x64.tar.gz -O /src/grafana.tar.gz

- name: Unzip grafana
  command: tar -xzf /src/grafana.tar.gz -C /opt/grafana --strip-components=1

- name: Remove temporary folder
  command: rm /src/grafana.tar.gz